{{- if .Values.bytesafe.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bytesafe.name" . }}
  labels:
    {{- include "bytesafe.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.bytesafe.ingress.annotations }}
    {{ toYaml .Values.bytesafe.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.bytesafe.ingress.ingressClassName }}
  ingressClassName: "{{ .Values.bytesafe.ingress.ingressClassName }}"
  {{- end }}
  rules:
    - host: "{{ include "domains.baseDomain" . }}"
      http:
        paths:
          - path: "{{ default "/" .Values.bytesafe.ingress.path }}"
            pathType: "{{ default "ImplementationSpecific" .Values.bytesafe.ingress.pathType }}"
            backend:
              service:
                name: "{{ include "bytesafe.service.name" . }}"
                port:
                  name: http
  {{- if .Values.bytesafe.ingress.tls }}
  tls:
    - hosts:
        - "{{ include "domains.baseDomain" . }}"
      secretName: "{{ include "domains.baseDomain.tls.secretName" . }}"
  {{- end }}
{{- end }}