{{- if not .Values.postgres.external.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "postgres.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "postgres.labels" . | nindent 8 }}
      annotations:
        checksum/cm-env: {{ include (print $.Template.BasePath "/postgres/cm-env.yaml") . | sha256sum }}
        {{- if .Values.postgres.podAnnotations }}
        {{ toYaml .Values.postgres.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{ toYaml .Values.commonAnnotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: "{{ default (include "postgres.name" . ) .Values.serviceAccount.postgres.name }}"
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.postgres.podSecurityContext | nindent 8 }}
      {{- with .Values.postgres.nodeSelector }}
      nodeSelector:
         {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgres.affinity }}
      affinity:
         {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgres.tolerations }}
      tolerations:
         {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.name }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.postgres.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ printf "%s-env" (include "postgres.name" .) }}"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            tcpSocket:
              port: 5432
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql

      volumes:
        {{- if not .Values.postgres.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- else if .Values.postgres.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.persistence.existingClaim }}
        {{- else }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s" (include "postgres.name" . ) }}
        {{- end }}
{{- end }}