{{- if and (not .Values.postgres.external.enabled) (.Values.serviceAccount.postgres.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ default (include "postgres.name" . ) .Values.serviceAccount.postgres.name }}"
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "postgres.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.postgres.annotations }}
    {{ toYaml .Values.serviceAccount.postgres.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
secrets:
  - name: {{ printf "%s-serviceaccount" (include "postgres.name" . ) }}
automountServiceAccountToken: true
{{- end }}
