{{- if .Values.bytesafe.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bytesafe.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels: {{- include "bytesafe.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bytesafe.name" . }}
  minReplicas: {{ .Values.bytesafe.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.bytesafe.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.bytesafe.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.bytesafe.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.bytesafe.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.bytesafe.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}